[tools]
golang = "1.22"
golangci-lint = "1.56.2"
"go:gotest.tools/gotestsum" = "v1.11.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"

[tasks.tests]
alias = "test"
description = "Run tests"
run = ["gotestsum", "golangci-lint run --allow-parallel-runners --fast"]

[tasks.fmt]
alias = "format"
description = "Format code"
run = ["goimports -w .", "go mod tidy"]

[tasks.build]
alias = "default"
description = "Build the project"
outputs = ["bin/binhost"]
run = ["go mod download", "go build -v -trimpath -o bin/ ./cmd/..."]

[tasks.dev]
depends = ["build"]
sources = ["cmd/**/*.go", "internal/**/*.go", "go.mod", "go.sum"]
env = { ENV = "development" }
run = ["./bin/binhost"]
