
# Default versions of tools, to update these, set [tools.override]
[tools]
golang = "1.23.4"
shfmt = "3"
golangci-lint = "1.56"
goreleaser = "latest"
"go:gotest.tools/gotestsum" = "v1.11.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"

[tasks.build]
description = "Build a binary for the current platform/architecture"
sources = ["cmd/**/*.go", "internal/**/*.go", "go.mod", "go.sum"]
outputs = ["./bin/binhost"]
run = "go build -trimpath -o ./bin/ -v ./cmd/..."

[tasks.test]
description = "Run tests"
run = "gotestsum"

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.fmt]
alias = "format"
description = "Format code"
run = [
  "go mod tidy",
  "gofmt -s -w .",
  "goimports -w .",
  "shfmt -w -i 2 -ci -sr .",
]

## <<Stencil::Block(custom)>>
[tasks.dev]
description = "Live reload target (use with `mise run watch`)"
depends = ["build"]
run = ["ENV=development ./bin/binhost"]

[tasks.watch]
description = "Watch for changes"
run = ["mise watch -t dev --clear --restart"]
## <</Stencil::Block>>
