services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    shm_size: 128mb
    ports:
      - "5432:5432/tcp"
    env_file: .env.development

  s3:
    image: minio/minio
    restart: on-failure
    ports:
      - "9000:9000/tcp"
      - "9001:9001/tcp"
    env_file: .env.development
    entrypoint:
      - /usr/bin/env
      - sh
      - -c
    command:
      - |-
        # Create the binhost bucket
        mkdir -vp /data/binhost
        exec /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"
