// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PkgsColumns holds the columns for the "pkgs" table.
	PkgsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
	}
	// PkgsTable holds the schema information for the "pkgs" table.
	PkgsTable = &schema.Table{
		Name:       "pkgs",
		Columns:    PkgsColumns,
		PrimaryKey: []*schema.Column{PkgsColumns[0]},
	}
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "target_pkgs", Type: field.TypeUUID, Nullable: true},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "targets_pkgs_pkgs",
				Columns:    []*schema.Column{TargetsColumns[2]},
				RefColumns: []*schema.Column{PkgsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PkgsTable,
		TargetsTable,
	}
)

func init() {
	TargetsTable.ForeignKeys[0].RefTable = PkgsTable
}
