// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jaredallard/binhost/internal/ent/pkg"
	"github.com/jaredallard/binhost/internal/ent/predicate"
	"github.com/jaredallard/binhost/internal/ent/target"
	"github.com/jaredallard/binhost/internal/parser"
)

// PkgUpdate is the builder for updating Pkg entities.
type PkgUpdate struct {
	config
	hooks    []Hook
	mutation *PkgMutation
}

// Where appends a list predicates to the PkgUpdate builder.
func (pu *PkgUpdate) Where(ps ...predicate.Pkg) *PkgUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetRepository sets the "repository" field.
func (pu *PkgUpdate) SetRepository(s string) *PkgUpdate {
	pu.mutation.SetRepository(s)
	return pu
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (pu *PkgUpdate) SetNillableRepository(s *string) *PkgUpdate {
	if s != nil {
		pu.SetRepository(*s)
	}
	return pu
}

// SetCategory sets the "category" field.
func (pu *PkgUpdate) SetCategory(s string) *PkgUpdate {
	pu.mutation.SetCategory(s)
	return pu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (pu *PkgUpdate) SetNillableCategory(s *string) *PkgUpdate {
	if s != nil {
		pu.SetCategory(*s)
	}
	return pu
}

// SetName sets the "name" field.
func (pu *PkgUpdate) SetName(s string) *PkgUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *PkgUpdate) SetNillableName(s *string) *PkgUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetVersion sets the "version" field.
func (pu *PkgUpdate) SetVersion(s string) *PkgUpdate {
	pu.mutation.SetVersion(s)
	return pu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pu *PkgUpdate) SetNillableVersion(s *string) *PkgUpdate {
	if s != nil {
		pu.SetVersion(*s)
	}
	return pu
}

// SetPackageFields sets the "package_fields" field.
func (pu *PkgUpdate) SetPackageFields(pc *parser.PackageCommon) *PkgUpdate {
	pu.mutation.SetPackageFields(pc)
	return pu
}

// SetTargetID sets the "target_id" field.
func (pu *PkgUpdate) SetTargetID(u uuid.UUID) *PkgUpdate {
	pu.mutation.SetTargetID(u)
	return pu
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (pu *PkgUpdate) SetNillableTargetID(u *uuid.UUID) *PkgUpdate {
	if u != nil {
		pu.SetTargetID(*u)
	}
	return pu
}

// SetTarget sets the "target" edge to the Target entity.
func (pu *PkgUpdate) SetTarget(t *Target) *PkgUpdate {
	return pu.SetTargetID(t.ID)
}

// Mutation returns the PkgMutation object of the builder.
func (pu *PkgUpdate) Mutation() *PkgMutation {
	return pu.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (pu *PkgUpdate) ClearTarget() *PkgUpdate {
	pu.mutation.ClearTarget()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PkgUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PkgUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PkgUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PkgUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PkgUpdate) check() error {
	if pu.mutation.TargetCleared() && len(pu.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pkg.target"`)
	}
	return nil
}

func (pu *PkgUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pkg.Table, pkg.Columns, sqlgraph.NewFieldSpec(pkg.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Repository(); ok {
		_spec.SetField(pkg.FieldRepository, field.TypeString, value)
	}
	if value, ok := pu.mutation.Category(); ok {
		_spec.SetField(pkg.FieldCategory, field.TypeString, value)
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(pkg.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Version(); ok {
		_spec.SetField(pkg.FieldVersion, field.TypeString, value)
	}
	if value, ok := pu.mutation.PackageFields(); ok {
		_spec.SetField(pkg.FieldPackageFields, field.TypeJSON, value)
	}
	if pu.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pkg.TargetTable,
			Columns: []string{pkg.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pkg.TargetTable,
			Columns: []string{pkg.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pkg.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PkgUpdateOne is the builder for updating a single Pkg entity.
type PkgUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PkgMutation
}

// SetRepository sets the "repository" field.
func (puo *PkgUpdateOne) SetRepository(s string) *PkgUpdateOne {
	puo.mutation.SetRepository(s)
	return puo
}

// SetNillableRepository sets the "repository" field if the given value is not nil.
func (puo *PkgUpdateOne) SetNillableRepository(s *string) *PkgUpdateOne {
	if s != nil {
		puo.SetRepository(*s)
	}
	return puo
}

// SetCategory sets the "category" field.
func (puo *PkgUpdateOne) SetCategory(s string) *PkgUpdateOne {
	puo.mutation.SetCategory(s)
	return puo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (puo *PkgUpdateOne) SetNillableCategory(s *string) *PkgUpdateOne {
	if s != nil {
		puo.SetCategory(*s)
	}
	return puo
}

// SetName sets the "name" field.
func (puo *PkgUpdateOne) SetName(s string) *PkgUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *PkgUpdateOne) SetNillableName(s *string) *PkgUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetVersion sets the "version" field.
func (puo *PkgUpdateOne) SetVersion(s string) *PkgUpdateOne {
	puo.mutation.SetVersion(s)
	return puo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (puo *PkgUpdateOne) SetNillableVersion(s *string) *PkgUpdateOne {
	if s != nil {
		puo.SetVersion(*s)
	}
	return puo
}

// SetPackageFields sets the "package_fields" field.
func (puo *PkgUpdateOne) SetPackageFields(pc *parser.PackageCommon) *PkgUpdateOne {
	puo.mutation.SetPackageFields(pc)
	return puo
}

// SetTargetID sets the "target_id" field.
func (puo *PkgUpdateOne) SetTargetID(u uuid.UUID) *PkgUpdateOne {
	puo.mutation.SetTargetID(u)
	return puo
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (puo *PkgUpdateOne) SetNillableTargetID(u *uuid.UUID) *PkgUpdateOne {
	if u != nil {
		puo.SetTargetID(*u)
	}
	return puo
}

// SetTarget sets the "target" edge to the Target entity.
func (puo *PkgUpdateOne) SetTarget(t *Target) *PkgUpdateOne {
	return puo.SetTargetID(t.ID)
}

// Mutation returns the PkgMutation object of the builder.
func (puo *PkgUpdateOne) Mutation() *PkgMutation {
	return puo.mutation
}

// ClearTarget clears the "target" edge to the Target entity.
func (puo *PkgUpdateOne) ClearTarget() *PkgUpdateOne {
	puo.mutation.ClearTarget()
	return puo
}

// Where appends a list predicates to the PkgUpdate builder.
func (puo *PkgUpdateOne) Where(ps ...predicate.Pkg) *PkgUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PkgUpdateOne) Select(field string, fields ...string) *PkgUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pkg entity.
func (puo *PkgUpdateOne) Save(ctx context.Context) (*Pkg, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PkgUpdateOne) SaveX(ctx context.Context) *Pkg {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PkgUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PkgUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PkgUpdateOne) check() error {
	if puo.mutation.TargetCleared() && len(puo.mutation.TargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Pkg.target"`)
	}
	return nil
}

func (puo *PkgUpdateOne) sqlSave(ctx context.Context) (_node *Pkg, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pkg.Table, pkg.Columns, sqlgraph.NewFieldSpec(pkg.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pkg.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pkg.FieldID)
		for _, f := range fields {
			if !pkg.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pkg.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Repository(); ok {
		_spec.SetField(pkg.FieldRepository, field.TypeString, value)
	}
	if value, ok := puo.mutation.Category(); ok {
		_spec.SetField(pkg.FieldCategory, field.TypeString, value)
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(pkg.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Version(); ok {
		_spec.SetField(pkg.FieldVersion, field.TypeString, value)
	}
	if value, ok := puo.mutation.PackageFields(); ok {
		_spec.SetField(pkg.FieldPackageFields, field.TypeJSON, value)
	}
	if puo.mutation.TargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pkg.TargetTable,
			Columns: []string{pkg.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pkg.TargetTable,
			Columns: []string{pkg.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(target.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pkg{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pkg.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
