// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/jaredallard/binhost/internal/ent/pkg"
	"github.com/jaredallard/binhost/internal/ent/schema"
	"github.com/jaredallard/binhost/internal/ent/target"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pkgFields := schema.Pkg{}.Fields()
	_ = pkgFields
	// pkgDescID is the schema descriptor for id field.
	pkgDescID := pkgFields[0].Descriptor()
	// pkg.DefaultID holds the default value on creation for the id field.
	pkg.DefaultID = pkgDescID.Default.(func() uuid.UUID)
	targetFields := schema.Target{}.Fields()
	_ = targetFields
	// targetDescID is the schema descriptor for id field.
	targetDescID := targetFields[0].Descriptor()
	// target.DefaultID holds the default value on creation for the id field.
	target.DefaultID = targetDescID.Default.(func() uuid.UUID)
}
