// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pkg is the predicate function for pkg builders.
type Pkg func(*sql.Selector)

// Target is the predicate function for target builders.
type Target func(*sql.Selector)
